sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t anydockerhubusername/frontend .

script:
  - docker run -e CI=true anydockerhubusername/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "$REGION_ID"
  app: "dockfend"
  env: "Dockfend-env"
  bucket_name: "elasticbeanstalk-$REGION_ID-$AWS_ACCOUNT_ID"
  only_create_app_version: "true"
  on:
    branch: master
