sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t anydockerhubusername/frontend .

script:
  - docker run -e CI=true anydockerhubusername/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockfrontend"
  env: "Dockfrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-745113398864"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"